# this is the build file for project cpp_lexer_generator
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

MXX=gcc
CXX=gcc
MM=gcc
CU=clang
CC=gcc
RC=rustc
AS=gcc
GC=go

GCAR=go
RCAR=rustc
SH=g++
RCSH=rustc
LD=g++
GCLD=go
RCLD=rustc


